# Generated by Django 3.2.7 on 2021-10-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='None', max_length=100, verbose_name='author name')),
                ('record_title', models.CharField(max_length=200, verbose_name='record title')),
                ('record_text', models.TextField(verbose_name='recoed text')),
            ],
        ),
    ]
